version: '3.8'

services:
  # Servicio de la Base de Datos PostgreSQL
  postgres:
    image: postgres:16-alpine
    container_name: library_postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: libraryDb1234*
      POSTGRES_DB: library_db
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Servicio de almacenamiento MinIO
  minio:
    image: minio/minio:latest
    container_name: library_minio
    restart: always
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin123
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - minio_data:/data
    healthcheck:
      test: ['CMD', 'mc', 'ready', 'local']
      interval: 5s
      timeout: 5s
      retries: 5

  # Servicio del Backend NestJS
  backend:
    build: .
    container_name: library_backend
    restart: always
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      DATABASE_URL: 'postgresql://admin:libraryDb1234*@postgres:5432/library_db?schema=public'
      JWT_SECRET: 'change-this-super-secret-key-in-production'
      JWT_EXPIRES_IN: '1d'
      MINIO_ENDPOINT: 'minio'
      MINIO_PORT: '9000'
      MINIO_PUBLIC_ENDPOINT: 'localhost'
      MINIO_PUBLIC_PORT: '9000'
      MINIO_USE_SSL: 'false'
      MINIO_ACCESS_KEY: 'minioadmin'
      MINIO_SECRET_KEY: 'minioadmin123'
      MINIO_BUCKET: 'books-images'
    command: sh -c "npm run prisma:setup && npm run start:dev"
    depends_on:
      - postgres
      - minio

  # Servicio del Frontend React (Vite)
  frontend:
    build: ./frontend
    container_name: library_frontend
    restart: always
    ports:
      - '5173:5173'
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:3000
    depends_on:
      - backend

volumes:
  postgres_data:
  minio_data:
